### PR TITLE
Fixing branch protection creation and adding missing restrictions

### PR DESCRIPTION
**Pull request by diequeiroz**
Safely checking if branch protection variable is set, if not, creating an empty array for contexts;

Avoiding overriding restrictions, when already set

### CODE REVIEW

**Comment by diequeiroz** [comment]
@SvanBoxel any thoughts?

**Comment by diequeiroz** [comment]
Fixes #44

**Comment by SvanBoxel** [comment]
This looks great, thank you so much. I'll merge and redeploy after the tests finish

**Review by SvanBoxel — APPROVED** [review]

**Comment by diequeiroz** [comment]
@SvanBoxel I did my best to ensure that updating the branch protection doesn't mess with the current settings, that's why I added the restrictions, that are only available on teams or enterprise plans. I did some tests and it seems the app doesn't interfere on things already set, but I think it's worth a double check.

**Pull request merged**
